### ISSUE TITLE
Show context menu menuitem even if there is selected text on the web page

### ISSUE THREAD

**Issue by Gitoffthelawn** [tqdv/save-page-now#1]
Thank you so much for this extension.  There are several similar to it, but this is the only one I find to be reliable.

I often use Firefox's `find` function on web pages.  I also frequently select text within web pages.  Unfortunately, once text is selected via the `find` function or via manual selection, the `Save Page Now` menuitem disappears.

Of course, one can deselect the text and open the page's context menu again, but that involves an additional step. (Plus another step to re-select the text.)

Would it be possible to show the extension's context menuitem even when text is selected?

**Comment by tqdv** [comment]
Thanks for the report. I implemented that in v0.1.3, and submitted it to addons.mozilla.org.

**Comment by Gitoffthelawn** [comment]
Thank you so much!
