### ISSUE TITLE
Change context menu menuitem strings

### ISSUE THREAD

**Issue by Gitoffthelawn** [tqdv/save-page-now#2]
What do you think about changing the English context menuitem strings from `Save Page Now` to `Archive Page Now` and from `Save Page Now (link)` to `Archive Link Now`?

**Comment by Gitoffthelawn** [comment]
I created a pull request for this: https://github.com/tqdv/save-page-now/pull/3

**Comment by tqdv** [comment]
Thanks for the PR, I merged it.

For the record, I named them that way because the feature of the Wayback Machine is called "Save Page Now".  
I think your suggestions do indeed make it clearer.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thanks again for the helpful extension.
